### ISSUE TITLE
Fix validation on Where and When page

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/consent-form-builder#316] opened 2018-06-12 12:59 UTC
Currently, if you select 'Yes' to the answer 'whether there is a set time and location', you can submit the form without entering any subsequent information. 

To fix this bug, the initial field of 'When' should be a mandatory field.

**Comment by ritapatel7** [comment] 2018-06-14 08:01
@joelcarr, I've estimated this as 3 as not sure if this needs updating from backend? Or can it be done from back end.

**Comment by joelcarr** [comment] 2018-06-14 09:48
It is a backend task. The new required validation is similar to the Incentives step.

**Comment by tosbourn** [comment] 2018-06-19 14:46
I was chatting to @sl33p about this – the current behaviour is the expected behaviour.

All of those fields are marked as optional, which they all are.

**Closed by tosbourn** 2018-06-19 14:46 UTC
Labels: estimate: 3, type: bug

**Comment by ritapatel7** [comment] 2018-06-20 07:40
@tosbourn @sl33p ... I had mentioned the same thing when discussing these tickets, that all fields are optional but I believe @kelliewellingtons raised this one because if we are asking user if the time and location is specified then we maybe should make the date and time and maybe location fields mandatory? Should this one be closed or discussed more or put in backlog and not necessarily do this one for this round/sprint?

**Comment by tosbourn** [comment] 2018-06-20 08:30
I think an immediate improvement would be #326 and then a longer discussion is required on why those fields were optional in the first place, there was presumably a use case for not making them required (fields being required was the default thinking the first time around).
